version: '2'
services:
    mysql:
        image: mysql:5.6
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=name

    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=name
            - POSTGRES_USER=name

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000 
        volumes:
            - .:/app/
        ports:
            - "8000:8000"
        links:
            - mysql 
            - postgres 
