version: '2'
services:
    mariadb:
        image: mariadb:10.5
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=name
            - MYSQL_USER=name
            - MYSQL_PASSWORD=name
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=name
            - POSTGRES_USER=name

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000 
        volumes:
            - .:/app/
        ports:
            - "8000:8000"
        links:
            - mariadb
            - postgres 
