[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "django-name"
description = "Name Authority App for Django."
readme = "README.md"
version = "6.0.0"
license = {file = 'LICENSE'}
keywords = ["django", "name", "citation"]
requires-python = ">=3.12"
authors = [
  { name = "University of North Texas Libraries", email = "mark.phillips@unt.edu" }
]
classifiers = [
  "Environment :: Web Environment",
  "Framework :: Django",
  "Intended Audience :: End Users/Desktop",
  "Natural Language :: English",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Application"
]
dependencies = [
    "python-dateutil==2.7.3",
    "markdown2>=2.4.0",
    "djangorestframework~=3.15.2",
    "pynaco==1.0.1",
]

[project.urls]
Homepage = "https://github.com/unt-libraries/django-name"
Repository = "https://github.com/unt-libraries/django-name"


[project.optional-dependencies]
dev = [
    "Django~=6.1",
    "django-debug-toolbar==3.8.1",
    "mysqlclient~=2.3.0",
]
test = [
    "markdown2>=2.4.0",
    "pytest>=7.1.0",
    "pytest-django>=4.6.2",
    "pytest-cov>=7.0.0",
    "psycopg2-binary>=2.9.9",
    "tomli>=2.0.1",
    "ruff~=0.15.9",
]

[tool.ruff]
line-length = 99
target-version = "py314"
extend-exclude = ['migrations']

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["E", "F", "W"]

[tool.tox]
legacy_tox_ini ='''
    [tox]
    envlist =
        py314-django61-{postgres,mariadb},
        ruff
        docs

    [testenv]
    passenv = DB_*
    allowlist_externals = ./runtests.py
    extras =
        test
        dev
    commands =
        mariadb: ./runtests.py {posargs} --nolint --ds=tests.settings.test_mariadb
        postgres: ./runtests.py {posargs} --nolint --ds=tests.settings.test_postgres

    [testenv:py3{12,13,14}-django61-mariadb]
    commands = 
        ./runtests.py {posargs} --nolint --ds=tests.settings.test_mariadb --cov=name
    allowlist_externals = ./runtests.py

    [testenv:ruff]
    skip_install = true
    deps = ruff
    commands =
        ruff check .

    [testenv:docs]
    deps = Sphinx>=4.0
    changedir = docs
    commands = {envbindir}/sphinx-build -W -b html . {envtmpdir}/html
'''
