# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0003_auto_20180917_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='type',
            field=models.ForeignKey(help_text="Catagorize this record's identifiers here", on_delete=django.db.models.deletion.CASCADE, to='name.Identifier_Type'),
        ),
        migrations.AlterField(
            model_name='identifier_type',
            name='homepage',
            field=models.URLField(blank=True, help_text='Homepage of label. Twitter.com, Facebook.com, etc'),
        ),
        migrations.AlterField(
            model_name='identifier_type',
            name='icon_path',
            field=models.CharField(blank=True, help_text='Path to icon image?', max_length=255),
        ),
        migrations.AlterField(
            model_name='identifier_type',
            name='label',
            field=models.CharField(help_text='What kind of data is this? Personal website? Twitter?', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=10, help_text='\n    <strong>\n        <a target="_blank" href="http://itouchmap.com/latlong.html">\n            iTouchMap\n        </a>\n        : this service might be useful for filling in the lat/long data\n    </strong>\n    ', max_digits=13),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=10, help_text='\n    <strong>\n        <a target="_blank" href="http://itouchmap.com/latlong.html">\n            iTouchMap\n        </a>\n        : this service might be useful for filling in the lat/long data\n    </strong>\n    ', max_digits=13),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.IntegerField(choices=[(0, 'current'), (1, 'former')], default=0),
        ),
        migrations.AlterField(
            model_name='name',
            name='begin',
            field=models.CharField(blank=True, help_text='Conforms to EDTF format YYYY-MM-DD', max_length=25),
        ),
        migrations.AlterField(
            model_name='name',
            name='biography',
            field=models.TextField(blank=True, help_text='Compatible with MARKDOWN'),
        ),
        migrations.AlterField(
            model_name='name',
            name='disambiguation',
            field=models.CharField(blank=True, help_text='Clarify to whom or what this record pertains.', max_length=255),
        ),
        migrations.AlterField(
            model_name='name',
            name='end',
            field=models.CharField(blank=True, help_text='Conforms to EDTF format YYYY-MM-DD', max_length=25),
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(help_text='Please use the general reverse order: LAST, FIRST', max_length=255),
        ),
        migrations.AlterField(
            model_name='name',
            name='name_type',
            field=models.IntegerField(choices=[(0, 'Personal'), (1, 'Organization'), (2, 'Event'), (3, 'Software'), (4, 'Building')]),
        ),
        migrations.AlterField(
            model_name='name',
            name='normalized_name',
            field=models.CharField(editable=False, help_text='NACO normalized form of the name', max_length=255),
        ),
        migrations.AlterField(
            model_name='name',
            name='record_status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Deleted'), (2, 'Suppressed')], default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(help_text='Enter notes about this record here'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.IntegerField(choices=[(0, 'Biographical/Historical'), (1, 'Deletion Information'), (2, 'Nonpublic'), (3, 'Source'), (4, 'Other')]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='normalized_variant',
            field=models.CharField(editable=False, help_text='NACO normalized variant text', max_length=255),
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant',
            field=models.CharField(help_text='Fill in the other name variants, if any.', max_length=255),
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant_type',
            field=models.IntegerField(choices=[(0, 'Acronym'), (1, 'Abbreviation'), (2, 'Translation'), (3, 'Expansion'), (4, 'Other')], help_text='Choose variant type.'),
        ),
    ]
