# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-23 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0004_auto_20191216_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=10, help_text='\n    <strong>\n        <a target="_blank" href="https://getlatlong.net">\n            getLatLong.net\n        </a>\n        : this service might be useful for filling in the lat/long data\n    </strong>\n    ', max_digits=13),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=10, help_text='\n    <strong>\n        <a target="_blank" href="https://getlatlong.net">\n            getLatLong.net\n        </a>\n        : this service might be useful for filling in the lat/long data\n    </strong>\n    ', max_digits=13),
        ),
    ]
